# Generated by Django 3.0.6 on 2020-05-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('image', models.CharField(max_length=30)),
            ],
        ),
    ]
