# Generated by Django 3.0.6 on 2020-05-30 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battlefield', models.SmallIntegerField(blank=True, null=True)),
                ('final_destination', models.SmallIntegerField(blank=True, null=True)),
                ('pokemon_stadium', models.SmallIntegerField(blank=True, null=True)),
                ('smashville', models.SmallIntegerField(blank=True, null=True)),
                ('town', models.SmallIntegerField(blank=True, null=True)),
                ('lylat', models.SmallIntegerField(blank=True, null=True)),
                ('kalos', models.SmallIntegerField(blank=True, null=True)),
                ('yoshi_story', models.SmallIntegerField(blank=True, null=True)),
                ('yoshi_island', models.SmallIntegerField(blank=True, null=True)),
                ('unova', models.SmallIntegerField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Character')),
            ],
        ),
    ]
