# Generated by Django 3.0.7 on 2020-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
