# Generated by Django 3.0.7 on 2020-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_character_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='small_battlefield',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
